-- =============================================
-- RustStats Full Database Schema
-- Run this in phpMyAdmin SQL tab
-- =============================================

-- Players table (all-time stats)
CREATE TABLE IF NOT EXISTS `players` (
  `id`              INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `steam_id`        VARCHAR(20)  NOT NULL UNIQUE,
  `display_name`    VARCHAR(64)  NOT NULL DEFAULT 'Unknown',
  `kills`           INT          NOT NULL DEFAULT 0,
  `deaths`          INT          NOT NULL DEFAULT 0,
  `kdr`             FLOAT        NOT NULL DEFAULT 0,
  `suicides`        INT          NOT NULL DEFAULT 0,
  `headshots`       INT          NOT NULL DEFAULT 0,
  `wounds`          INT          NOT NULL DEFAULT 0,
  `bullets_fired`   INT          NOT NULL DEFAULT 0,
  `bullet_hits`     INT          NOT NULL DEFAULT 0,
  `longest_kill`    FLOAT        NOT NULL DEFAULT 0,
  `competitive_kills` INT        NOT NULL DEFAULT 0,
  `oilrig_kills`    INT          NOT NULL DEFAULT 0,
  `oilrig_deaths`   INT          NOT NULL DEFAULT 0,
  `heli_kills`      INT          NOT NULL DEFAULT 0,
  `diving_kills`    INT          NOT NULL DEFAULT 0,
  `sub_kills`       INT          NOT NULL DEFAULT 0,
  `self_wounds`     INT          NOT NULL DEFAULT 0,
  `animal_kills`    INT          NOT NULL DEFAULT 0,
  `npc_kills`       INT          NOT NULL DEFAULT 0,
  `bradley_kills`   INT          NOT NULL DEFAULT 0,
  `boats_destroyed` INT          NOT NULL DEFAULT 0,
  `subs_destroyed`  INT          NOT NULL DEFAULT 0,
  `wood`            BIGINT       NOT NULL DEFAULT 0,
  `stone`           BIGINT       NOT NULL DEFAULT 0,
  `metal`           BIGINT       NOT NULL DEFAULT 0,
  `sulfur`          BIGINT       NOT NULL DEFAULT 0,
  `hqm`             BIGINT       NOT NULL DEFAULT 0,
  `leather`         BIGINT       NOT NULL DEFAULT 0,
  `animal_fat`      BIGINT       NOT NULL DEFAULT 0,
  `bone`            BIGINT       NOT NULL DEFAULT 0,
  `blocks_placed`   INT          NOT NULL DEFAULT 0,
  `blocks_upgraded` INT          NOT NULL DEFAULT 0,
  `deployables`     INT          NOT NULL DEFAULT 0,
  `doors_placed`    INT          NOT NULL DEFAULT 0,
  `wiring_meters`   FLOAT        NOT NULL DEFAULT 0,
  `piping_meters`   FLOAT        NOT NULL DEFAULT 0,
  `hose_meters`     FLOAT        NOT NULL DEFAULT 0,
  `c4_used`         INT          NOT NULL DEFAULT 0,
  `satchels_used`   INT          NOT NULL DEFAULT 0,
  `hv_rockets`      INT          NOT NULL DEFAULT 0,
  `rockets_used`    INT          NOT NULL DEFAULT 0,
  `online_hits`     INT          NOT NULL DEFAULT 0,
  `offline_hits`    INT          NOT NULL DEFAULT 0,
  `crates_looted`   INT          NOT NULL DEFAULT 0,
  `barrels_broken`  INT          NOT NULL DEFAULT 0,
  `crates_freed`    INT          NOT NULL DEFAULT 0,
  `fish_gutted`     INT          NOT NULL DEFAULT 0,
  `cloth`           BIGINT       NOT NULL DEFAULT 0,
  `yellow_berries`  BIGINT       NOT NULL DEFAULT 0,
  `red_berries`     BIGINT       NOT NULL DEFAULT 0,
  `blue_berries`    BIGINT       NOT NULL DEFAULT 0,
  `green_berries`   BIGINT       NOT NULL DEFAULT 0,
  `white_berries`   BIGINT       NOT NULL DEFAULT 0,
  `mushrooms`       BIGINT       NOT NULL DEFAULT 0,
  `pumpkins`        BIGINT       NOT NULL DEFAULT 0,
  `corn`            BIGINT       NOT NULL DEFAULT 0,
  `potatoes`        BIGINT       NOT NULL DEFAULT 0,
  `wheat`           BIGINT       NOT NULL DEFAULT 0,
  `flowers`         BIGINT       NOT NULL DEFAULT 0,
  `eggs`            BIGINT       NOT NULL DEFAULT 0,
  `purchases`       INT          NOT NULL DEFAULT 0,
  `sales`           INT          NOT NULL DEFAULT 0,
  `items_bought`    INT          NOT NULL DEFAULT 0,
  `items_sold`      INT          NOT NULL DEFAULT 0,
  `drone_purchases` INT          NOT NULL DEFAULT 0,
  `scrap_wagered`   BIGINT       NOT NULL DEFAULT 0,
  `scrap_won`       BIGINT       NOT NULL DEFAULT 0,
  `barrel_scrap`    BIGINT       NOT NULL DEFAULT 0,
  `crate_scrap`     BIGINT       NOT NULL DEFAULT 0,
  `recycler_scrap`  BIGINT       NOT NULL DEFAULT 0,
  `playtime`        INT          NOT NULL DEFAULT 0,
  `items_dropped`   INT          NOT NULL DEFAULT 0,
  `missions_started` INT         NOT NULL DEFAULT 0,
  `missions_done`   INT          NOT NULL DEFAULT 0,
  `time_swimming`   FLOAT        NOT NULL DEFAULT 0,
  `distance_walked` FLOAT        NOT NULL DEFAULT 0,
  `teleport_home`   INT          NOT NULL DEFAULT 0,
  `teleport_tpr`    INT          NOT NULL DEFAULT 0,
  `teleport_outpost` INT         NOT NULL DEFAULT 0,
  `teleport_total`  INT          NOT NULL DEFAULT 0,
  `last_updated`    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_kills` (`kills` DESC),
  KEY `idx_kdr`   (`kdr`   DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Clans table
CREATE TABLE IF NOT EXISTS `clans` (
  `id`           INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `tag`          VARCHAR(16) NOT NULL UNIQUE,
  `name`         VARCHAR(64) NOT NULL DEFAULT '',
  `owner_id`     VARCHAR(20) NOT NULL DEFAULT '',
  `member_count` INT         NOT NULL DEFAULT 0,
  `total_kills`  INT         NOT NULL DEFAULT 0,
  `total_deaths` INT         NOT NULL DEFAULT 0,
  `clan_kdr`     FLOAT       NOT NULL DEFAULT 0,
  `total_c4`     INT         NOT NULL DEFAULT 0,
  `total_rockets` INT        NOT NULL DEFAULT 0,
  `total_wood`   BIGINT      NOT NULL DEFAULT 0,
  `total_stone`  BIGINT      NOT NULL DEFAULT 0,
  `total_sulfur` BIGINT      NOT NULL DEFAULT 0,
  `last_updated` DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Online players table (live RCON tracking)
CREATE TABLE IF NOT EXISTS `online_players` (
  `steam_id`     VARCHAR(20) NOT NULL PRIMARY KEY,
  `display_name` VARCHAR(64) NOT NULL DEFAULT '',
  `last_seen`    DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Wipes table
CREATE TABLE IF NOT EXISTS `wipes` (
  `wipe_id`    INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `start_date` DATE        NOT NULL,
  `end_date`   DATE,
  `label`      VARCHAR(64) NOT NULL,
  `is_current` TINYINT(1)  NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Per-wipe player stats
CREATE TABLE IF NOT EXISTS `player_wipe_stats` (
  `id`              INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `wipe_id`         INT          NOT NULL,
  `steam_id`        VARCHAR(20)  NOT NULL,
  `display_name`    VARCHAR(64)  NOT NULL DEFAULT 'Unknown',
  `kills`           INT          NOT NULL DEFAULT 0,
  `deaths`          INT          NOT NULL DEFAULT 0,
  `kdr`             FLOAT        NOT NULL DEFAULT 0,
  `suicides`        INT          NOT NULL DEFAULT 0,
  `headshots`       INT          NOT NULL DEFAULT 0,
  `wounds`          INT          NOT NULL DEFAULT 0,
  `bullets_fired`   INT          NOT NULL DEFAULT 0,
  `bullet_hits`     INT          NOT NULL DEFAULT 0,
  `longest_kill`    FLOAT        NOT NULL DEFAULT 0,
  `competitive_kills` INT        NOT NULL DEFAULT 0,
  `oilrig_kills`    INT          NOT NULL DEFAULT 0,
  `oilrig_deaths`   INT          NOT NULL DEFAULT 0,
  `heli_kills`      INT          NOT NULL DEFAULT 0,
  `diving_kills`    INT          NOT NULL DEFAULT 0,
  `sub_kills`       INT          NOT NULL DEFAULT 0,
  `self_wounds`     INT          NOT NULL DEFAULT 0,
  `animal_kills`    INT          NOT NULL DEFAULT 0,
  `npc_kills`       INT          NOT NULL DEFAULT 0,
  `bradley_kills`   INT          NOT NULL DEFAULT 0,
  `boats_destroyed` INT          NOT NULL DEFAULT 0,
  `subs_destroyed`  INT          NOT NULL DEFAULT 0,
  `wood`            BIGINT       NOT NULL DEFAULT 0,
  `stone`           BIGINT       NOT NULL DEFAULT 0,
  `metal`           BIGINT       NOT NULL DEFAULT 0,
  `sulfur`          BIGINT       NOT NULL DEFAULT 0,
  `hqm`             BIGINT       NOT NULL DEFAULT 0,
  `leather`         BIGINT       NOT NULL DEFAULT 0,
  `animal_fat`      BIGINT       NOT NULL DEFAULT 0,
  `bone`            BIGINT       NOT NULL DEFAULT 0,
  `blocks_placed`   INT          NOT NULL DEFAULT 0,
  `blocks_upgraded` INT          NOT NULL DEFAULT 0,
  `deployables`     INT          NOT NULL DEFAULT 0,
  `doors_placed`    INT          NOT NULL DEFAULT 0,
  `wiring_meters`   FLOAT        NOT NULL DEFAULT 0,
  `piping_meters`   FLOAT        NOT NULL DEFAULT 0,
  `hose_meters`     FLOAT        NOT NULL DEFAULT 0,
  `c4_used`         INT          NOT NULL DEFAULT 0,
  `satchels_used`   INT          NOT NULL DEFAULT 0,
  `hv_rockets`      INT          NOT NULL DEFAULT 0,
  `rockets_used`    INT          NOT NULL DEFAULT 0,
  `online_hits`     INT          NOT NULL DEFAULT 0,
  `offline_hits`    INT          NOT NULL DEFAULT 0,
  `crates_looted`   INT          NOT NULL DEFAULT 0,
  `barrels_broken`  INT          NOT NULL DEFAULT 0,
  `crates_freed`    INT          NOT NULL DEFAULT 0,
  `fish_gutted`     INT          NOT NULL DEFAULT 0,
  `cloth`           BIGINT       NOT NULL DEFAULT 0,
  `yellow_berries`  BIGINT       NOT NULL DEFAULT 0,
  `red_berries`     BIGINT       NOT NULL DEFAULT 0,
  `blue_berries`    BIGINT       NOT NULL DEFAULT 0,
  `green_berries`   BIGINT       NOT NULL DEFAULT 0,
  `white_berries`   BIGINT       NOT NULL DEFAULT 0,
  `mushrooms`       BIGINT       NOT NULL DEFAULT 0,
  `pumpkins`        BIGINT       NOT NULL DEFAULT 0,
  `corn`            BIGINT       NOT NULL DEFAULT 0,
  `potatoes`        BIGINT       NOT NULL DEFAULT 0,
  `wheat`           BIGINT       NOT NULL DEFAULT 0,
  `flowers`         BIGINT       NOT NULL DEFAULT 0,
  `eggs`            BIGINT       NOT NULL DEFAULT 0,
  `purchases`       INT          NOT NULL DEFAULT 0,
  `sales`           INT          NOT NULL DEFAULT 0,
  `items_bought`    INT          NOT NULL DEFAULT 0,
  `items_sold`      INT          NOT NULL DEFAULT 0,
  `drone_purchases` INT          NOT NULL DEFAULT 0,
  `scrap_wagered`   BIGINT       NOT NULL DEFAULT 0,
  `scrap_won`       BIGINT       NOT NULL DEFAULT 0,
  `barrel_scrap`    BIGINT       NOT NULL DEFAULT 0,
  `crate_scrap`     BIGINT       NOT NULL DEFAULT 0,
  `recycler_scrap`  BIGINT       NOT NULL DEFAULT 0,
  `playtime`        INT          NOT NULL DEFAULT 0,
  `items_dropped`   INT          NOT NULL DEFAULT 0,
  `missions_started` INT         NOT NULL DEFAULT 0,
  `missions_done`   INT          NOT NULL DEFAULT 0,
  `time_swimming`   FLOAT        NOT NULL DEFAULT 0,
  `distance_walked` FLOAT        NOT NULL DEFAULT 0,
  `teleport_home`   INT          NOT NULL DEFAULT 0,
  `teleport_tpr`    INT          NOT NULL DEFAULT 0,
  `teleport_outpost` INT         NOT NULL DEFAULT 0,
  `teleport_total`  INT          NOT NULL DEFAULT 0,
  `last_updated`    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `wipe_player` (`wipe_id`, `steam_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
